export const registerUrl = 'register'
export const loginUrl = 'login'
export const logoutUrl = 'logout'
export const upPicUrl = 'upPic'
export const upVideoUrl = 'upVideo'
export const upFileUrl = 'upFile'