export const registerUrl = 'register'
export const loginUrl = 'login'
export const logoutUrl = 'logout'
export const searchUserUrl = 'searchUser'
export const addUserUrl = 'addUser'
export const getContactsUrl = 'getContacts'